name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build
        env:
          DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/specstar'
          BETTER_AUTH_SECRET: 'test-secret-for-ci-32-chars-minimum'
          BETTER_AUTH_URL: 'http://localhost:3000'
          NEXT_PUBLIC_BASE_URL: 'http://localhost:3000'

      - name: Run type checking
        run: pnpm typecheck
        continue-on-error: true

      - name: Run linting
        run: pnpm lint
        continue-on-error: true

      - name: Run tests
        run: pnpm test
        continue-on-error: true