name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  deploy-platform:
    name: Deploy Platform
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build platform for production
        run: pnpm --filter @specstar/platform build
        env:
          NODE_ENV: production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
          BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}
          NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Deploy to Vercel
        if: ${{ vars.DEPLOY_TARGET == 'vercel' }}
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./apps/platform

  release-cli:
    name: Release CLI
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build shared packages
        run: pnpm --filter @specstar/shared build

      - name: Build CLI
        run: pnpm --filter @specstar/cli build

      - name: Build CLI binaries
        run: |
          cd apps/cli
          bun build --compile --outfile=dist/specstar-linux-x64 --target=bun-linux-x64 src/cli.tsx
          bun build --compile --outfile=dist/specstar-darwin-x64 --target=bun-darwin-x64 src/cli.tsx
          bun build --compile --outfile=dist/specstar-darwin-arm64 --target=bun-darwin-arm64 src/cli.tsx
          bun build --compile --outfile=dist/specstar-windows-x64.exe --target=bun-windows-x64 src/cli.tsx

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: cli-v${{ github.run_number }}
          name: CLI Release ${{ github.run_number }}
          draft: true
          files: |
            apps/cli/dist/specstar-linux-x64
            apps/cli/dist/specstar-darwin-x64
            apps/cli/dist/specstar-darwin-arm64
            apps/cli/dist/specstar-windows-x64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}